// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lirwrsfnhdqdkmsgvdym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxpcndyc2ZuaGRxZGttc2d2ZHltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjE5MDcsImV4cCI6MjA2MTQzNzkwN30.PB4u8tDuPcQDxl8HGApoRfMLwc6pWhciDOCoNVqfhaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);