// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpvpgdnpegzskcnnoejy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwdnBnZG5wZWd6c2tjbm5vZWp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NTM4NzYsImV4cCI6MjA1OTEyOTg3Nn0.XvWPTo5799O-gi7V9gLGRcHjeLfV4Qw7ssjGuoj_wE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);